// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'NewsItemsJsonData.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Items _$ItemsFromJson(Map<String, dynamic> json) {
  return Items(
    json['bbstxSnDatatype'] as String?,
    json['newsTitl'] as String?,
    json['newsWrterNmDatatype'] as String?,
    json['natnDatatype'] as String?,
    json['indstClDatatype'] as String?,
    json['regnDatatype'] as String?,
    json['kotraNewsUrlDatatype'] as String?,
    json['regDtDatatype'] as String?,
    json['crrspOvrofLink'] as String?,
    json['newsBdtDatatype'] as String?,
    json['indstCl'] as String?,
    json['newsBdt'] as String?,
    json['newsWrtDt'] as String?,
    json['newsTitlDatatype'] as String?,
    json['bbstxSn'] as String?,
    json['inqreCnt'] as String?,
    json['infoCl'] as String?,
    json['updDtDatatype'] as String?,
    json['natn'] as String?,
    json['inqryItmLinkDatatype'] as String?,
    json['infoClDatatype'] as String?,
    json['kotraNewsUrl'] as String?,
    json['newsWrtDtDatatype'] as String?,
    json['inqreCntDatatype'] as String?,
    json['kwrdDatatype'] as String?,
    json['kwrd'] as String?,
    json['regn'] as String?,
    json['regDt'] as String?,
    json['newsBdtDatanotice'] as String?,
    json['cntntSumar'] as String?,
    json['ovrofInfoDatatype'] as String?,
    json['ovrofInfo'] as String?,
    json['inqryItmLink'] as String?,
    json['newsWrterNm'] as String?,
    json['updDt'] as String?,
    json['cntntSumarDatatype'] as String?,
    json['crrspOvrofLinkDatatype'] as String?,
  );
}

Map<String, dynamic> _$ItemsToJson(Items instance) => <String, dynamic>{
      'bbstxSnDatatype': instance.bbstxSnDatatype,
      'newsTitl': instance.newsTitl,
      'newsWrterNmDatatype': instance.newsWrterNmDatatype,
      'natnDatatype': instance.natnDatatype,
      'indstClDatatype': instance.indstClDatatype,
      'regnDatatype': instance.regnDatatype,
      'kotraNewsUrlDatatype': instance.kotraNewsUrlDatatype,
      'regDtDatatype': instance.regDtDatatype,
      'crrspOvrofLink': instance.crrspOvrofLink,
      'newsBdtDatatype': instance.newsBdtDatatype,
      'indstCl': instance.indstCl,
      'newsBdt': instance.newsBdt,
      'newsWrtDt': instance.newsWrtDt,
      'newsTitlDatatype': instance.newsTitlDatatype,
      'bbstxSn': instance.bbstxSn,
      'inqreCnt': instance.inqreCnt,
      'infoCl': instance.infoCl,
      'updDtDatatype': instance.updDtDatatype,
      'natn': instance.natn,
      'inqryItmLinkDatatype': instance.inqryItmLinkDatatype,
      'infoClDatatype': instance.infoClDatatype,
      'kotraNewsUrl': instance.kotraNewsUrl,
      'newsWrtDtDatatype': instance.newsWrtDtDatatype,
      'inqreCntDatatype': instance.inqreCntDatatype,
      'kwrdDatatype': instance.kwrdDatatype,
      'kwrd': instance.kwrd,
      'regn': instance.regn,
      'regDt': instance.regDt,
      'newsBdtDatanotice': instance.newsBdtDatanotice,
      'cntntSumar': instance.cntntSumar,
      'ovrofInfoDatatype': instance.ovrofInfoDatatype,
      'ovrofInfo': instance.ovrofInfo,
      'inqryItmLink': instance.inqryItmLink,
      'newsWrterNm': instance.newsWrterNm,
      'updDt': instance.updDt,
      'cntntSumarDatatype': instance.cntntSumarDatatype,
      'crrspOvrofLinkDatatype': instance.crrspOvrofLinkDatatype,
    };
